import * as dotenv from "dotenv";
dotenv.config();

export const includedTypes: string[] = [
  "car_dealer",
  "car_rental",
  "car_repair",
  "car_wash",
  "electric_vehicle_charging_station",
  "gas_station",
  "parking",
  "dental_clinic",
  "dentist",
  "apartment_building",
  "barber_shop",
  "beauty_salon",
  "consultant",
  "electrician",
  "florist",
  "hair_salon",
  "insurance_agency",
  "lawyer",
  "locksmith",
  "real_estate_agency",
  "roofing_contractor",
  "storage",
  "tailor",
  "telecommunications_service_provider",
  "travel_agency",
  "veterinary_care",
  "auto_parts_store",
  "bicycle_store",
  "book_store",
  "cell_phone_store",
  "clothing_store",
  "convenience_store",
  "department_store",
  "discount_store",
  "electronics_store",
  "furniture_store",
  "hardware_store",
  "home_goods_store",
  "jewelry_store",
  "market",
  "pet_store",
  "shoe_store",
  "sporting_goods_store",
  "fitness_center",
  "gym",
];

// All places types provided here: https://developers.google.com/maps/documentation/places/web-service/place-types